### PR TITLE
[WIP] travis: support osx and python 3.4

### PR DESCRIPTION
**Pull request by smola**
Signed-off-by: Santiago M. Mola <santi@mola.io>

### CODE REVIEW

**Comment by smola** [comment]
No Python support on OS X for Travis CI at the moment: https://github.com/travis-ci/travis-ci/issues/2312
Possible workarounds exist (they are discussed in the issue above), such as https://github.com/MacPython/terryfy

**Comment by juanjux** [comment]
@smola so is this ready to merge or a WIP? (I see that CI was failing, I guess for the reason you wrote).

**Comment by smola** [comment]
@juanjux WIP, I need to figure out the right way to setup Python on macOS. it should be using official Python.org installers, which should be fast and also it is the only way to generate macOS wheels.

**Comment by smola** [comment]
Closing, this will just not work in its current form.

**Pull request closed without merging**
