### PR TITLE
Fix memory leaks (thanks @amlweems)

### PR DESCRIPTION
**Pull request by juanjux**
(Branched from amlweems:fix-memory-leak)

- Apply the memory leaks [detected and fixed by @amlweems](https://github.com/bblfsh/client-python/pull/74) with an aditional one for the `String` helper functions that allows the fix for `ItemAt` to work.

- Test (also from @amlweems branch) to check that memory doesn't increase after 100 `filter()` calls. 

Signed-off-by: Juanjo Alvarez <juanjo@sourced.tech>

### CODE REVIEW

**Comment by juanjux** [comment]
cc @amlweems

**Comment by amlweems** [comment]
Nice! Testing with `pympler` again, this fixes the major memory leak. And the objects that are still around don't scale with the number of iterations I do against `filter()`.

```
# 5000 iterations of filter()
        types |   # objects |   total size
============= | =========== | ============
  <class list |        5056 |    555.20 KB
   <class str |        5045 |    438.51 KB
   <class int |        1003 |     43.10 KB
...

# 10000 iterations of filter()
        types |   # objects |   total size
============= | =========== | ============
  <class list |        5056 |    555.20 KB
   <class str |        5045 |    438.51 KB
   <class int |        1003 |     43.10 KB
...
```

I tried running with cpython and valgrind. I get a lot of "possibly lost", but no worrying "definitely lost". I'm not super confident in these results, but I am very happy with the object counts above. [Full output attached.](https://github.com/bblfsh/client-python/files/1682043/leaks.txt)

```
# cpython build conf
./configure --without-pymalloc --with-pydebug --with-valgrind --prefix=`pwd`/build

# valgrind command
valgrind --tool=memcheck --suppressions=/tmp/cpython/Misc/valgrind-python.supp --log-file=leaks.txt --leak-check=full python -m unittest bblfsh.test.BblfshTests.testManyFilters
```

```
==21838== LEAK SUMMARY:
==21838==    definitely lost: 40 bytes in 1 blocks
==21838==    indirectly lost: 0 bytes in 0 blocks
==21838==      possibly lost: 6,314,378 bytes in 37,480 blocks
==21838==    still reachable: 193,285 bytes in 310 blocks
==21838==         suppressed: 0 bytes in 0 blocks
```

**Comment by juanjux** [comment]
@vmarkovtsev that would be certainly great, I used a simpler tool that doesn't Python to recompile called memleak, I'm pretty sure current leaks are fixed since I increased locally the iterations in the memory test to 100.000 and the memory didn't increase, but I'll give a run with Valgrind when I've a little time.

On the other side, Travis is failing with a core dump while works perfectly on my machine :/

**Comment by vmarkovtsev** [comment]
@amlweems This leak summary gives a solid confidence that all the leaks are fixed, awesome!

**Comment by juanjux** [comment]
Found the reason why it works on my machine(TM) and not in Travis... when testing for leaks, I set the environment variable "PYTHONMALLOC" to "malloc" since that allows the `memleak` command to find the leaks. With that environment variable set, it works, without it, it segfaults. Looks like I'm for another debugging session :-1:

**Comment by juanjux** [comment]
Looks like the problem comes from mixing malloc with pymalloc in the same extension module. This is not a problem for shared libraries, but since libuast is compiled with the extension module it causes problems. The solutions I'm evaluating are requiring and using `libuast.so` or adding a function to libuast to pass the alloc/free functions to use.

**Comment by juanjux** [comment]
Ok, the pointer-between-mallocs problem is hellish and using the `libuast.so` crashed just the same, so I did a workaround that while not perfect will avoid the leak: I store the problematic PyObjects in a PyList  and free (DECREF) it at the end of Python's `filter()` wrapper when libuast is not touching them anymore for sure.

**Comment by vmarkovtsev** [comment]
Amazing detective work @juanjux !

**Pull request merged**
